# Generated by Django 2.0.5 on 2018-06-01 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish_name', models.CharField(max_length=200)),
                ('total_ingredients', models.IntegerField(blank=True, null=True)),
                ('spice', models.CharField(choices=[('BLAND', 'BLAND'), ('MILD', 'MILD'), ('HOT', 'HOT'), ('INFERNO', 'INFERNO')], default='BLAND', max_length=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'dishes',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='dish',
            field=models.ManyToManyField(blank=True, to='store.Dish'),
        ),
    ]
