# Generated by Django 2.0.5 on 2018-06-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180531_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
