# Generated by Django 2.0.5 on 2018-06-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_dish_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='spice',
        ),
    ]
