# Generated by Django 2.0.5 on 2018-06-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_dish_spice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dish',
            field=models.ManyToManyField(blank=True, related_name='category', to='store.Dish'),
        ),
    ]
