# Generated by Django 2.0.5 on 2018-06-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='address',
        ),
    ]
