# Generated by Django 2.0.5 on 2018-06-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20180614_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='store_name',
            field=models.CharField(default='new location', max_length=100),
        ),
    ]
