# Generated by Django 2.0.5 on 2018-06-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_location_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(default='East Coast', max_length=50),
        ),
    ]
